services:
  bot:
    build: .
    restart: always
    env_file:
      - .env_docker
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env_docker
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env_docker

volumes:
  db:
  minio-data:
  minio-config:
